/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ams;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class PayBillPanel extends javax.swing.JFrame {

    /**
     * Creates new form PayBillPanel
     */
    
    private Tool tool = new Tool();
    ResidentAccount rAccount = new ResidentAccount();
    String billID = "";
    
    //Constructor
    public PayBillPanel(ResidentAccount rAccount, String billID) {
        initComponents();
        this.rAccount = rAccount;
        this.billID = billID;
        setDetails();
        tool.displayDate(date);
        tool.displayTime(time);
    }
    
    public PayBillPanel(){
        initComponents();
        tool.displayDate(date);
        tool.displayTime(time);
    }
    
    //Setting details to the panel by pulling data from database
    private void setDetails(){
        Dbclass db = new Dbclass();
        Connection con = null;
        PreparedStatement pst = null;
        ResultSet rs = null;
        
        try {
            con = db.connectDB();
            String sql = "SELECT bills.billType, bills.billAmount, bills.issueDate, resident.residentName " +
                         "FROM bills " +
                         "INNER JOIN resident ON bills.accountIDBills=resident.accountRDBID " +
                         "where bills.accountIDBills = ? and resident.relationshipToOwner = \"SELF\" and " +
                         "bills.billID = ?";
            pst = con.prepareStatement(sql);
            pst.setString(1, rAccount.getAccountIDFromDB());
            pst.setString(2, this.billID);
            rs = pst.executeQuery();
            
            if (rs.next()){
                billIDLabel.setText(this.billID);
                payableAmountLabel.setText("RM " + rs.getString("billAmount"));
                nameLabel.setText(rs.getString("residentName"));
                typeLabel.setText(rs.getString("billType"));
                issueDateLabel.setText(rs.getString("issueDate"));
            }
        } catch (Exception e){
            e.printStackTrace();
        } finally {
            try { pst.close(); } catch (Exception e) { e.printStackTrace();}
            try { con.close(); } catch (Exception e) { e.printStackTrace();}
            try { rs.close(); } catch (Exception e) { e.printStackTrace();}
        }
    }
    
    //Pay bill function to pay the bill and change the status from "UNPAID" to "PAID" or "PAID_LATE"
    private boolean payBill(){
        Dbclass db = new Dbclass();
        Connection con = null;
        PreparedStatement pst = null;
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        Date dateToInsert = new Date();
        
        try {
            con = db.connectDB();
            String sql = "UPDATE bills SET status = 'PAID', payDate = ? WHERE billID = ?;";
            pst = con.prepareStatement(sql);
            pst.setString(1, dateFormat.format(dateToInsert));
            pst.setString(2, billIDLabel.getText());
            int update = pst.executeUpdate();
            
            return update > 0;
        } catch (Exception e){
            e.printStackTrace();
            return false;
        } finally {
            try { pst.close(); } catch (Exception e) { e.printStackTrace();}
            try { con.close(); } catch (Exception e) { e.printStackTrace();}
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        billIDLabel = new javax.swing.JLabel();
        payableAmountLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        issueDateLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        date = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("AMS | Confirm Payment");
        setAutoRequestFocus(false);
        setFocusTraversalPolicyProvider(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(247, 127, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Type:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Bill ID:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Payable Amount:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Name:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        typeLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        typeLabel.setForeground(new java.awt.Color(255, 255, 255));
        typeLabel.setText("-");
        jPanel1.add(typeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 360, -1));

        billIDLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        billIDLabel.setForeground(new java.awt.Color(255, 255, 255));
        billIDLabel.setText("-");
        jPanel1.add(billIDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 360, -1));

        payableAmountLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        payableAmountLabel.setForeground(new java.awt.Color(255, 255, 255));
        payableAmountLabel.setText("-");
        jPanel1.add(payableAmountLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 360, -1));

        nameLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel.setText("-");
        jPanel1.add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 360, -1));

        issueDateLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        issueDateLabel.setForeground(new java.awt.Color(255, 255, 255));
        issueDateLabel.setText("-");
        jPanel1.add(issueDateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 360, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Issue Date:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Pay");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 160, 30));

        jButton2.setBackground(new java.awt.Color(0, 204, 51));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 160, 30));

        jPanel2.setBackground(new java.awt.Color(0, 48, 73));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        date.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        date.setForeground(new java.awt.Color(255, 255, 255));
        date.setText("0");
        jPanel2.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 110, -1));

        time.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        time.setForeground(new java.awt.Color(255, 255, 255));
        time.setText("0");
        jPanel2.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 80, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Confirm Payment");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 608, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(624, 396));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        HomePage hp = new HomePage(rAccount);
        hp.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(payBill()){
            tool.getInformationMessageOptionPane("Paid successfully!");
            this.dispose();
            HomePage hp = new HomePage(rAccount);
            hp.setVisible(true);
            return;
        }
        tool.getErrorMessageOptionPane("Something went wrong! Payment unsuccessful!");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PayBillPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PayBillPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PayBillPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PayBillPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PayBillPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel billIDLabel;
    private javax.swing.JLabel date;
    private javax.swing.JLabel issueDateLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel payableAmountLabel;
    private javax.swing.JLabel time;
    private javax.swing.JLabel typeLabel;
    // End of variables declaration//GEN-END:variables
}
